### ISSUE TITLE
Bug Serialization of lower_quality.txt fails

### ISSUE THREAD

**Issue by AliSot2000** [elisemercury/Duplicate-Image-Finder#110]
Serializing the list of lower quality files fails. By the looks of it, instead of the paths, the np.ndarray objects are passed into the lower_quailty leading to a `TypeError: Object of type ndarray is not JSON serializable`

This is the full shell output:
```bash
(lv2) alisot2000@AliSot2000-Linux-ROG-Zephyrus-G14:~/Desktop/lv2/lib/python3.12/site-packages/difPy$ python3 dif.py -D /home/alisot2000/Desktop/test-dirs2/dir_a/ /home/alisot2000/Desktop/test-dirs2/dir_b/ /home/alisot2000/Desktop/test-dirs2/dir_c/ -Z /home/alisot2000/Desktop/test-dirs2/ -mv /home/alisot2000/Desktop/test-dirs2/output/ -s 66
Error DecompressionBombWarning loading image #14 : '/home/alisot2000/Desktop/test-dirs2/dir_a/Panorama 2.jpg' -> Image size (118755328 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
Error DecompressionBombWarning loading image #109 : '/home/alisot2000/Desktop/test-dirs2/dir_c/Panorama 2.jpg' -> Image size (118755328 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
difPy preparing files: [100%]
difPy searching files: [100%]
Moved 74 files(s) to "/home/alisot2000/Desktop/test-dirs2/output"
Traceback (most recent call last):
  File "/home/alisot2000/Desktop/lv2/lib/python3.12/site-packages/difPy/dif.py", line 1029, in <module>
    json.dump(se.lower_quality, file)
  File "/usr/lib/python3.12/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.12/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/usr/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
```

**Comment by elisemercury** [comment]
Hi @AliSot2000, 

Thanks a lot for reporting this bug! This will definitely be considered for the upcoming update.

**Comment by elisemercury** [comment]
Hi @AliSot2000,

Thanks again for filing this issue! We have implemented a fix for this as part of [version 4.2.0](https://github.com/elisemercury/Duplicate-Image-Finder/releases/tag/v4.2.0).

Thanks,
Elise
