### ISSUE TITLE
FEATURE delete vs move ambiguous if both provided

### ISSUE THREAD

**Issue by AliSot2000** [elisemercury/Duplicate-Image-Finder#111]
Providing the script with the flags `-mv /path/to/dir -d` causes the script to move the files and afterwards error out when printing stats about the deleted files.

```bash
Moved 0 files(s) to "/home/alisot2000/Desktop/test-dirs2/output"
Traceback (most recent call last):
  File "/home/alisot2000/Desktop/lv2/lib/python3.12/site-packages/difPy/dif.py", line 1034, in <module>
    se.delete(silent_del=args.silent_del)
  File "/home/alisot2000/Desktop/lv2/lib/python3.12/site-packages/difPy/dif.py", line 690, in delete
    print(f'Deleted {deleted_files} file(s)')
                     ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'deleted_files' where it is not associated with a value
```

Suggestions for improvement:
1. Define a priority (and document it) which argument takes precedent if both are provided
2. Raise an Error if both are specified.

**Comment by elisemercury** [comment]
Hi @AliSot2000, 

Thanks a lot for flagging this! This will definitely be considered for the upcoming update.

**Comment by elisemercury** [comment]
Hi @AliSot2000,

Thanks again for filing this issue! We have implemented a fix for this as part of [version 4.2.0](https://github.com/elisemercury/Duplicate-Image-Finder/releases/tag/v4.2.0).

Thanks,
Elise
